# Generated by Django 4.2.15 on 2024-09-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_remove_bank_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='www.account'),
            preserve_default=False,
        ),
    ]
