# Generated by Django 4.2.15 on 2024-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_account_name_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
