# Generated by Django 4.2.15 on 2024-10-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_alter_transaction_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
